// Code generated by hertz generator.

package police_service

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnearestpolicestationsMw() []app.HandlerFunc {
	// your code...
	return nil
}
