// Code generated by hertz generator.

package poi_density

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	poi "github.com/renxingdawang/SDataHK/biz/model/poi_density"
	service "github.com/renxingdawang/SDataHK/biz/service/poi"
)

// GetPOIDensity .
// @router /poi [GET]
func GetPOIDensity(ctx context.Context, c *app.RequestContext) {
	//var err error
	//var req poi.POIDensityRequest
	req := poi.POIDensityRequest{
		Latitude:  22.396428,
		Longitude: 114.109497,
		Radius:    1000.0,
	}
	err := c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, err := service.NewPOIService(ctx, c).GetPOIDensity(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp)
}
