// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/renxingdawang/SDataHK/biz/dal"
)

func Init() {
	dal.Init()
}
func main() {
	Init()
	h := server.Default(
		server.WithStreamBody(true),
		server.WithHostPorts("127.0.0.1:18005"),
	)
	register(h)
	h.Spin()
}
