// Code generated by hertz generator.

package poi_density

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpoidensityMw() []app.HandlerFunc {
	// your code...
	return nil
}
