// Code generated by hertz generator.

package water_pollution

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpollutionsourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}
