// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	poi_density "github.com/renxingdawang/SDataHK/biz/router/poi_density"
	police_service "github.com/renxingdawang/SDataHK/biz/router/police_service"
	urban "github.com/renxingdawang/SDataHK/biz/router/urban"
	water_pollution "github.com/renxingdawang/SDataHK/biz/router/water_pollution"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	urban.Register(r)

	poi_density.Register(r)

	water_pollution.Register(r)

	police_service.Register(r)
}
