// Code generated by hertz generator.

package urban

import (
	"context"
	service "github.com/renxingdawang/SDataHK/biz/service/urban"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	urban "github.com/renxingdawang/SDataHK/biz/model/urban"
)

// AnalyzeUrbanHeatIsland .
// @router /urban [GET]
func AnalyzeUrbanHeatIsland(ctx context.Context, c *app.RequestContext) {
	var err error
	//var req urban.UrbanHeatIslandRequest
	req := urban.UrbanHeatIslandRequest{
		Longitude: 114.109497, // 香港经度
		Latitude:  22.396428,  // 香港纬度
		Radius:    5000.0,     // 半径 5000 米
	}
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := service.NewUrbanHeatIslandService(ctx, c).AnalyzeUrbanHeatIsland(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
