// Code generated by hertz generator.

package water_pollution

import (
	"context"
	service "github.com/renxingdawang/SDataHK/biz/service/police"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	pollution "github.com/renxingdawang/SDataHK/biz/model/water_pollution"
)

// GetPollutionSources .
// @router /pollution [GET]
func GetPollutionSources(ctx context.Context, c *app.RequestContext) {
	//var err error
	//var req water_pollution.WaterPollutionRequest
	req := pollution.WaterPollutionRequest{
		Longitude: 114.109497, // 香港经度
		Latitude:  22.396428,  // 香港纬度
		Radius:    5000.0,     // 半径 5000 米
	}
	err := c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp, err := service.NewPollutionService(ctx, c).GetPollutionSources(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	c.JSON(consts.StatusOK, resp)
}
