// Code generated by hertz generator.

package urban

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _analyzeurbanheatislandMw() []app.HandlerFunc {
	// your code...
	return nil
}
